Lint/NotNil:
  Enabled: false

Lint/Formatting:
  Excluded:
    - src/lib/gphoto2/camera.cr
    - src/lib/gphoto2/camera_filesystem.cr
    - src/lib/gphoto2/gp_context.cr

Naming/BinaryOperatorParameterName:
  Excluded:
    - src/gphoto2/camera/filesystem.cr
    - src/gphoto2/camera_folder.cr
